remote_theme: pages-themes/hacker@v0.2.0
plugins:
 - jekyll-default-layout
 - jekyll-github-metadata
 - jekyll-readme-index
 - jekyll-remote-theme
title: Crimson.Lab
description: Лаборатория Кримсона
excerpt_separator: <!--more-->
url: "https://x-crm.in"
assets:
  sources:
    - assets/blog
    - assets/css
    - assets/fonts
    - assets/images
    - assets/js