---
layout: post
title: "Проектируем 3D модель с ИИ"
description: "Инженерка в scad/stl"
tags: 3d scad stl
---

# Проектируем 3D модель с ИИ
Пришло время проверить, как ИИ может рисовать инженерные 3D модели.

## Вентиляционная решётка с раструбом и воронкой:
 * Назначение: накладка на вентиляционную шахту 150×150 мм с подключением горизонтального воздуховода 210×60 мм и зоной естественной вентиляции через решётку.
 * Ориентация (для печати и сборки):

 * z=0 — основание пластины (ложится на стол принтера)
 * Collar (раструб) уходит вверх (+Z), при монтаже — в шахту
 * Декоративные элементы выступают вверх (+Z), в ту же сторону что и collar

**Общая геометрия:**

 * **Пластина:** 210×210×3 мм (монолитная, цельное основание без разрывов)
 * **Шахта:** 150×150 мм, центрирована в пластине (отступ 30 мм по периметру)

**Зонирование пластины (по Y, снизу вверх):**
```
y = 0..30     — нижний периметр (зона логотипа)
y = 30..90    — зона воздуховода (collar + воронка)
y = 90..93    — разделительная перемычка (3 мм)
y = 93..180   — зона решётки (5 ламелей)
y = 180..210  — верхний периметр
```
**Collar (раструб):**

 * Внешний размер: 210×60 мм
 * Глубина: 30 мм (выступает вверх от пластины)
 * Стенка: 3 мм
 * Углы: скруглённые, R=5 мм снаружи
 * Внутри — воронка (frustum): 150 мм (у пластины) плавно расширяется до 204 мм (на выходе collar). Высота воронки (Y) постоянная — 54 мм. Обеспечивает плавный переход воздуха из шахты в широкий канал

**Отверстие в пластине под collar:**

 * Вырез повторяет внутренний контур воронки на уровне пластины: 150×54 мм
 * Пластина вокруг collar остаётся цельной — вырезается только проход воздуха

**Решётка:**

 * Зона: 150×87 мм (внутри проёма шахты, выше воздуховода)
 * 5 горизонтальных ламелей, толщина 3 мм
 * Зазор между ламелями: ~12 мм (крупный шаг для естественной вентиляции)
 * Разделительная перемычка 150×3×3 мм между зоной collar и решёткой

**Крепёж:**

 * 4 отверстия ⌀4 мм в углах пластины
 * Отступ от краёв: 15 мм по обеим осям
 * Отверстия проходят через всю толщину детали

**Материал/печать:**

 * **Стенки:** 3 мм (основная версия), 0.8 мм (тестовая для примерки)
 * **Тестовая версия: **ламели тоже 0.8 мм
 * Все поверхности watertight, готово к слайсеру
 * **Габарит:** 210×210×33 мм — требует разбиения или диагональной ориентации для принтеров с малым столом

## Результат
{% include stl-viewer.html model="/assets/blog/3d-vent-grille/vent_grille.stl" %}

**Claude 4.6** создал модель [stl](/assets/blog/3d-vent-grille/vent_grille.stl)+[scad](/assets/blog/3d-vent-grille/vent_grille.scad) с помощью **Python** - **trimesh + manifold3d**

*И [3D просмотрщик stl файлов](/2026/02/12/jekyll-widget-stl-viewer.html) для этого поста, так же был создан Claude 4.6*

## Отправляем на печать
{% include youtube.html id="oh5DIHs1A9Q" %}