esphome:
  name: servo
  friendly_name: servo

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "***"

captive_portal:

i2c:
  - scan: True
ttp229_lsf:
  - address: 0x65

binary_sensor:
  - platform: ttp229_lsf
    name: "Button R1 Max"
    id: button_r1_max
    channel: 7
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 100%
 
  - platform: ttp229_lsf
    name: "Button R1 Min"
    id: button_r1_min
    channel: 3
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%

  - platform: ttp229_lsf
    name: "Button R1 Only"
    id: button_r1_only
    channel: 15
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 100%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: ttp229_lsf
    name: "Button R2 Max"
    id: button_r2_max
    channel: 6
    on_press: 
      then:
        - servo.write: 
            id: servo_r2
            level: 100%

  - platform: ttp229_lsf
    name: "Button R2 Min"
    id: button_r2_min
    channel: 2
    on_press: 
      then:
        - servo.write: 
            id: servo_r2
            level: 0%

  - platform: ttp229_lsf
    name: "Button R2 Only"
    id: button_r2_only
    channel: 14
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 100%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: ttp229_lsf
    name: "Button R3 Max"
    id: button_r3_max
    channel: 5
    on_press: 
      then:
        - servo.write: 
            id: servo_r3
            level: 100%

  - platform: ttp229_lsf
    name: "Button R3 Min"
    id: button_r3_min
    channel: 1
    on_press: 
      then:
        - servo.write: 
            id: servo_r3
            level: 0%

  - platform: ttp229_lsf
    name: "Button R3 Only"
    id: button_r3_only
    channel: 13
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 100%
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: ttp229_lsf
    name: "Button R4 Max"
    id: button_r4_max
    channel: 4
    on_press: 
      then:
        - servo.write: 
            id: servo_r4
            level: 100%

  - platform: ttp229_lsf
    name: "Button R4 Min"
    id: button_r4_min
    channel: 0
    on_press: 
      then:
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: ttp229_lsf
    name: "Button R4 Only"
    id: button_r4_only
    channel: 12
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 100%

  - platform: ttp229_lsf
    name: "Open ALL"
    id: button_open_all
    channel: 11
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 100%
        - servo.write: 
            id: servo_r2
            level: 100%
        - servo.write: 
            id: servo_r3
            level: 100%
        - servo.write: 
            id: servo_r4
            level: 100%

  - platform: ttp229_lsf
    name: "Close ALL"
    id: button_close_all
    channel: 8
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 0%

servo:
  - id: servo_r1
    output: pwm_output_r1
  - id: servo_r2
    output: pwm_output_r2
  - id: servo_r3
    output: pwm_output_r3
  - id: servo_r4
    output: pwm_output_r4

output:
  - platform: esp8266_pwm
    id: pwm_output_r1
    pin: D4
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r2
    pin: D5
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r3
    pin: D6
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r4
    pin: D7
    frequency: 50 Hz
