esphome:
  name: servo
  friendly_name: servo

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "***"

captive_portal:

#  D1 ( GPIO5 )
#  D2 ( GPIO4 )
#  D5 ( GPIO14 )
#  D6 ( GPIO12 )
#  D7 ( GPIO13 )
# Example configuration entry
servo:
  - id: servo_r1
    output: pwm_output_r1
  - id: servo_r2
    output: pwm_output_r2
  - id: servo_r3
    output: pwm_output_r3
  - id: servo_r4
    output: pwm_output_r4

output:
  - platform: esp8266_pwm
    id: pwm_output_r1
    pin: D4
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r2
    pin: D5
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r3
    pin: D6
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r4
    pin: D7
    frequency: 50 Hz

sensor:
  - platform: adc
    pin: A0
    name: "Analog Keypad Value"
    update_interval: 100ms
    filters:
      - throttle: 100ms
      - delta: 0.01
    on_value:
      then:
        - lambda: |-
            float voltage = x; // x is the raw value from the ADC
            if (voltage < 0.1) {
              // No button pressed
            } else if (voltage >= 0.95 && voltage <= 1) {
              // 1
              id(button_r1_max).publish_state(true);
              id(servo_r1).write(1.0);
            } else if (voltage >= 0.85 && voltage <= 0.9) {
              // 088
              id(button_r1_min).publish_state(true);
              id(servo_r1).write(0.0);
            } else if (voltage >= 0.68 && voltage <= 0.72) {
              // 070
              id(button_r2_max).publish_state(true);
              id(servo_r2).write(1.0);
            } else if (voltage >= 0.58 && voltage <= 0.65) {
              // 061
              id(button_r2_min).publish_state(true);
              id(servo_r2).write(0.0);
            } else if (voltage >= 0.50 && voltage <= 0.55) {
              // 052
              id(button_r3_max).publish_state(true);
              id(servo_r3).write(1.0);
            } else if (voltage >= 0.45 && voltage <= 0.49) {
              // 047
              id(button_r3_min).publish_state(true);
              id(servo_r3).write(0.0);
            } else if (voltage >= 0.38 && voltage <= 0.43) {
              // 041
              id(button_r4_max).publish_state(true);
              id(servo_r1).write(1.0);
              id(servo_r2).write(1.0);
              id(servo_r3).write(1.0);
              id(servo_r4).write(1.0);
            } else if (voltage >= 0.26 && voltage <= 0.32) {
              // 028
              id(button_r4_min).publish_state(true);
              id(servo_r1).write(0.0);
              id(servo_r2).write(0.0);
              id(servo_r3).write(0.0);
              id(servo_r4).write(0.0);
            }
            // Add more conditions for each button
            else {
              // Unknown button or no button pressed
              // Reset all buttons to false
              id(button_r1_max).publish_state(false);
              id(button_r1_min).publish_state(false);
              id(button_r2_max).publish_state(false);
              id(button_r2_min).publish_state(false);
              id(button_r3_max).publish_state(false);
              id(button_r3_min).publish_state(false);
              id(button_r4_max).publish_state(false);
              id(button_r4_min).publish_state(false);
              // Add more button resets
            }

binary_sensor:
  - platform: template
    name: "Button R1 Max"
    id: button_r1_max
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R1 Min"
    id: button_r1_min
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R2 Max"
    id: button_r2_max
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R2 Min"
    id: button_r2_min
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R3 Max"
    id: button_r3_max
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R3 Min"
    id: button_r3_min
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R4 Max"
    id: button_r4_max
    filters:
      - delayed_off: 100ms
  - platform: template
    name: "Button R4 Min"
    id: button_r4_min
    filters:
      - delayed_off: 100ms