esphome:
  name: servo
  friendly_name: servo

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "***"

captive_portal:

i2c:
  - scan: True
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false
matrix_keypad:
  id: mykeypad
  rows:
    - pin:
        pcf8574: pcf8574_hub
        number: 0
        mode: OUTPUT
        inverted: False
    - pin:
        pcf8574: pcf8574_hub
        number: 1
        mode: OUTPUT
        inverted: False        
    - pin:
        pcf8574: pcf8574_hub
        number: 2
        mode: OUTPUT
        inverted: False
    - pin:
        pcf8574: pcf8574_hub
        number: 3
        mode: OUTPUT
        inverted: False
  columns:
    - pin:
        pcf8574: pcf8574_hub
        number: 4
        mode: INPUT
        inverted: False
    - pin:
        pcf8574: pcf8574_hub
        number: 5
        mode: INPUT
        inverted: False
    - pin:
        pcf8574: pcf8574_hub
        number: 6
        mode: INPUT
        inverted: False
    - pin:
        pcf8574: pcf8574_hub
        number: 7
        mode: INPUT
        inverted: False
  keys: "123A456B789C*0#D"


binary_sensor:
  - platform: matrix_keypad
    name: "Button R1 Max"
    id: button_r1_max
    key: "1"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 100%
 
  - platform: matrix_keypad
    name: "Button R1 Min"
    id: button_r1_min
    key: "2"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%

  - platform: matrix_keypad
    name: "Button R1 Only"
    id: button_r1_only
    key: "3"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 100%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: matrix_keypad
    name: "Button R2 Max"
    id: button_r2_max
    key: "4"
    on_press: 
      then:
        - servo.write: 
            id: servo_r2
            level: 100%

  - platform: matrix_keypad
    name: "Button R2 Min"
    id: button_r2_min
    key: "5"
    on_press: 
      then:
        - servo.write: 
            id: servo_r2
            level: 0%

  - platform: matrix_keypad
    name: "Button R2 Only"
    id: button_r2_only
    key: "6"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 100%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: matrix_keypad
    name: "Button R3 Max"
    id: button_r3_max
    key: "7"
    on_press: 
      then:
        - servo.write: 
            id: servo_r3
            level: 100%

  - platform: matrix_keypad
    name: "Button R3 Min"
    id: button_r3_min
    key: "8"
    on_press: 
      then:
        - servo.write: 
            id: servo_r3
            level: 0%

  - platform: matrix_keypad
    name: "Button R3 Only"
    id: button_r3_only
    key: "9"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 100%
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: matrix_keypad
    name: "Button R4 Max"
    id: button_r4_max
    key: "*"
    on_press: 
      then:
        - servo.write: 
            id: servo_r4
            level: 100%

  - platform: matrix_keypad
    name: "Button R4 Min"
    id: button_r4_min
    key: "0"
    on_press: 
      then:
        - servo.write: 
            id: servo_r4
            level: 0%

  - platform: matrix_keypad
    name: "Button R4 Only"
    id: button_r4_only
    key: "#"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 100%

  - platform: matrix_keypad
    name: "Open ALL"
    id: button_open_all
    key: "A"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 100%
        - servo.write: 
            id: servo_r2
            level: 100%
        - servo.write: 
            id: servo_r3
            level: 100%
        - servo.write: 
            id: servo_r4
            level: 100%

  - platform: matrix_keypad
    name: "Close ALL"
    id: button_close_all
    key: "D"
    on_press: 
      then:
        - servo.write: 
            id: servo_r1
            level: 0%
        - servo.write: 
            id: servo_r2
            level: 0%
        - servo.write: 
            id: servo_r3
            level: 0%
        - servo.write: 
            id: servo_r4
            level: 0%

servo:
  - id: servo_r1
    output: pwm_output_r1
  - id: servo_r2
    output: pwm_output_r2
  - id: servo_r3
    output: pwm_output_r3
  - id: servo_r4
    output: pwm_output_r4

output:
  - platform: esp8266_pwm
    id: pwm_output_r1
    pin: D4
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r2
    pin: D5
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r3
    pin: D6
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_r4
    pin: D7
    frequency: 50 Hz


#  D1 ( GPIO5 )
#  D2 ( GPIO4 )
#  D5 ( GPIO14 )
#  D6 ( GPIO12 )
#  D7 ( GPIO13 )
# Example configuration entry