#remote_theme: pages-themes/hacker@v0.2.0
plugins:
 - jekyll-default-layout
 - jekyll-github-metadata
 - jekyll-readme-index
#- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Crimson.Lab
description: Лаборатория Кримсона
excerpt_separator: <!--more-->